name: Remote SSH
on: [push]
jobs:

  build:
   - name: pass environment
     uses: appleboy/ssh-action@master
     env:
       FOO: "BAR"
       BAR: "FOO"
       SHA: ${{ github.sha }}
     with:
       host: ${{ secrets.IP }}
       username: ${{ secrets.USERNAME }}
       key: ${{ secrets.PRIVATE_KEY }}
       port: ${{ secrets.PORT }}
       envs: FOO,BAR
       script: |
         echo "I am $FOO"
         echo "I am $BAR"
         echo "sha: $SHA"
