name: Remote SSH
on: [push]
jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Remote SSH
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.IP }}
        username: ${{ secrets.USER }}
        key: ${{ secrets.PRIVATE_KEY }}
        script: |
          cd /root/errbot_root && git pull ;
          systemctl restart errbot;
          systemctl status errbot;
          systemctl restart wg-quick@wghub.service;
          cd /root/ git add wgclient* && git commit -m "update wgclient" && git push;